//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.TrajetService")]
    public interface TrajetService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrajetService/submit", ReplyAction="http://tempuri.org/TrajetService/submitResponse")]
        string submit(string d, string a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrajetService/submit", ReplyAction="http://tempuri.org/TrajetService/submitResponse")]
        System.Threading.Tasks.Task<string> submitAsync(string d, string a);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrajetServiceChannel : Client.ServiceReference1.TrajetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrajetServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.TrajetService>, Client.ServiceReference1.TrajetService {
        
        public TrajetServiceClient() {
        }
        
        public TrajetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrajetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrajetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrajetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string submit(string d, string a) {
            return base.Channel.submit(d, a);
        }
        
        public System.Threading.Tasks.Task<string> submitAsync(string d, string a) {
            return base.Channel.submitAsync(d, a);
        }
    }
}
